name: fleetctl-gitops
description: Runs fleetctl gitops to apply configuration to Fleet

inputs:
  working-directory:
    description: 'The working directory, which should be the root of the repository.'
    default: './'
  dry-run-only:
    description: 'Whether to only run the fleetctl gitops commands in dry-run mode.'
    default: 'false'
  delete-other-fleets:
    description: 'Whether to delete any other fleets which exist in the database but are not defined as .yml.'
    default: 'true'

runs:
  using: "composite"
  steps:
    - name: Restore fleetctl cache
      uses: actions/cache/restore@v4
      id: fleetctl-cache
      with:
        path: /tmp/fleet/build
        key: fleetctl-my-key

    - name: Clone fleet repository
      if: steps.fleetctl-cache.outputs.cache-hit != 'true'
      shell: bash
      run: git clone --branch main --depth 1 https://github.com/fleetdm/fleet.git /tmp/fleet

    - name: Set up Go
      if: steps.fleetctl-cache.outputs.cache-hit != 'true'
      uses: actions/setup-go@v5
      with:
        go-version-file: /tmp/fleet/go.mod

    - name: Build fleetctl
      if: steps.fleetctl-cache.outputs.cache-hit != 'true'
      shell: bash
      working-directory: /tmp/fleet
      run: make fleetctl

    - name: Add fleetctl to PATH
      shell: bash
      run: echo "/tmp/fleet/build" >> "$GITHUB_PATH"

    - name: Save fleetctl cache
      if: steps.fleetctl-cache.outputs.cache-hit != 'true'
      uses: actions/cache/save@v4
      with:
        path: /tmp/fleet/build
        key: fleetctl-my-key

    - name: Configure fleetctl
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: fleetctl config set --address ${{ env.FLEET_URL }} --token ${{ env.FLEET_API_TOKEN }}

    - name: Run fleetctl gitops commands
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      env:
        FLEET_DRY_RUN_ONLY: ${{ inputs.dry-run-only }}
        FLEET_DELETE_OTHER_FLEETS: ${{ inputs.delete-other-fleets }}
      run: ./.github/fleet-gitops/gitops.sh
